### ISSUE TITLE
SyntaxError: Unexpected token 'export' when using in nextjs

### ISSUE THREAD

**Issue by macrozone** [Scrivito/scroll-to-fragment#11]
there is something wrong with the build, it still contains export import syntax.

I thought that this work if you specify `module` entrypoint in package.json, but a short test did not work

**Comment by dcsaszar** [comment]
Hey @macrozone,

thanks for the input.

So far the package requires a development environments with `export` support.
I lazily assumed that all modern:tm: build tools/frameworks have this.

If this issue happens with a recent version of `create-next-app`, we should try to be more cross-environment.

Could you please quickly describe the steps necessary to reproduce the issue?

**Comment by dcsaszar** [comment]
Closing for now. Will reopen if there is more information.

**Comment by macrozone** [comment]
@dcsaszar sorry, i did not end up using this library, because it did not work for my case.
