### ISSUE TITLE
In page links are not working

### ISSUE THREAD

**Issue by cbou** [Scrivito/scroll-to-fragment#13]
Does this package works for links that stays in the page?
e.g. a button with link target with only `#bottom`

**Comment by dcsaszar** [comment]
@cbou 

Yes, it should work

[Here's](https://github.com/Scrivito/scroll-to-fragment/blob/master/spec/index.spec.ts#L47-L57) our test for this case.

However, if your app for some reason swallows the click event, or the URL change is triggered programmatically, you will have to configure `scroll-to-fragment` accordingly.
Typically this means you have to pass your History integration in the `history` option.

**Comment by dcsaszar** [comment]
FYI currently, `scroll-to-fragment` doesn't work with `history` version 5. We'll prepare an update.

**Comment by cbou** [comment]
Thanks 👍 
You are right it works now. Except if I load the Scrivito editor then the link does not work...

**Comment by dcsaszar** [comment]
Please note that while `scroll-to-fragment` works with `history` version 5, `scrivito` depends on `history` version 4.
See https://npm.anvaka.com/#/view/2d/scrivito for the dependency graph.

Please make sure to use `history` 4.x when passing it to `Scrivito.useHistory()`.

Regarding HTML links in in-place editing (edit mode) - yes, you cannot click them to navigate. Editing has priority.
